import io.netty.resolver.dns.DnsResolveContext.DnsResolveContextException;
public class FunctionUse3782 {
public void funcUse() {
DnsResolveContextException dnsresolvecontextexception = new DnsResolveContextException();
}
}